ALTER TABLE `member_stores`
  ADD COLUMN IF NOT EXISTS `contact_phone_area_code` VARCHAR(5) DEFAULT NULL COMMENT '聯絡人市話區碼' AFTER `contact_name`,
  ADD COLUMN IF NOT EXISTS `integration_hash_key` VARCHAR(255) DEFAULT NULL AFTER `payment_tools`,
  ADD COLUMN IF NOT EXISTS `integration_iv_key` VARCHAR(255) DEFAULT NULL AFTER `integration_hash_key`,
  ADD COLUMN IF NOT EXISTS `integration_notify_url` VARCHAR(255) DEFAULT NULL AFTER `integration_iv_key`,
  ADD COLUMN IF NOT EXISTS `integration_return_url` VARCHAR(255) DEFAULT NULL AFTER `integration_notify_url`,
  ADD COLUMN IF NOT EXISTS `integration_test_mode` TINYINT(1) NOT NULL DEFAULT 0 AFTER `integration_return_url`,
  ADD COLUMN IF NOT EXISTS `integration_credit_card_api_enabled` TINYINT(1) NOT NULL DEFAULT 1 AFTER `integration_test_mode`,
  ADD COLUMN IF NOT EXISTS `integration_refund_api_enabled` TINYINT(1) NOT NULL DEFAULT 1 AFTER `integration_credit_card_api_enabled`,
  ADD COLUMN IF NOT EXISTS `integration_token_api_enabled` TINYINT(1) NOT NULL DEFAULT 1 AFTER `integration_refund_api_enabled`,
  ADD COLUMN IF NOT EXISTS `integration_non_card_refund_api_enabled` TINYINT(1) NOT NULL DEFAULT 1 AFTER `integration_token_api_enabled`,
  ADD COLUMN IF NOT EXISTS `integration_logistics_refund_api_enabled` TINYINT(1) NOT NULL DEFAULT 1 AFTER `integration_non_card_refund_api_enabled`,
  ADD COLUMN IF NOT EXISTS `integration_linepay_refund_api_enabled` TINYINT(1) NOT NULL DEFAULT 1 AFTER `integration_logistics_refund_api_enabled`,
  ADD COLUMN IF NOT EXISTS `integration_member_free_api_enabled` TINYINT(1) NOT NULL DEFAULT 1 AFTER `integration_linepay_refund_api_enabled`,
  ADD COLUMN IF NOT EXISTS `integration_discount_refund_api_enabled` TINYINT(1) NOT NULL DEFAULT 0 AFTER `integration_member_free_api_enabled`,
  ADD COLUMN IF NOT EXISTS `integration_street_payment_refund_api_enabled` TINYINT(1) NOT NULL DEFAULT 1 AFTER `integration_discount_refund_api_enabled`,
  ADD COLUMN IF NOT EXISTS `integration_allowed_ips` TEXT DEFAULT NULL AFTER `integration_street_payment_refund_api_enabled`,
  ADD COLUMN IF NOT EXISTS `e_invoice_enabled` TINYINT(1) NOT NULL DEFAULT 0 AFTER `integration_allowed_ips`,
  ADD COLUMN IF NOT EXISTS `e_invoice_center` VARCHAR(100) DEFAULT NULL AFTER `e_invoice_enabled`,
  ADD COLUMN IF NOT EXISTS `e_invoice_gift_unit` VARCHAR(30) DEFAULT NULL AFTER `e_invoice_center`,
  ADD COLUMN IF NOT EXISTS `e_invoice_auto_issue` TINYINT(1) NOT NULL DEFAULT 1 AFTER `e_invoice_gift_unit`,
  ADD COLUMN IF NOT EXISTS `e_invoice_delay_days` TINYINT UNSIGNED DEFAULT NULL AFTER `e_invoice_auto_issue`,
  ADD COLUMN IF NOT EXISTS `transaction_amount_limit_enabled` TINYINT(1) NOT NULL DEFAULT 1 AFTER `e_invoice_delay_days`,
  ADD COLUMN IF NOT EXISTS `expired_refund_enabled` TINYINT(1) NOT NULL DEFAULT 0 AFTER `transaction_amount_limit_enabled`,
  ADD COLUMN IF NOT EXISTS `transaction_card_limit_mode` VARCHAR(20) NOT NULL DEFAULT 'off' AFTER `expired_refund_enabled`,
  ADD COLUMN IF NOT EXISTS `transaction_ip_limit_mode` VARCHAR(20) NOT NULL DEFAULT 'off' AFTER `transaction_card_limit_mode`,
  ADD COLUMN IF NOT EXISTS `marketing_enabled` TINYINT(1) NOT NULL DEFAULT 0 AFTER `transaction_ip_limit_mode`,
  ADD COLUMN IF NOT EXISTS `marketing_notes` VARCHAR(400) DEFAULT NULL AFTER `marketing_enabled`;
